import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistMono = Roboto_Mono({
  weight: ["400", "500", "700"],
  style: "normal",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.className}  antialiased`}>{children}</body>
    </html>
  );
}
